services:
  - type: web
    name: data-scientist
    runtime: python
    region: frankfurt  # ya apna nearest region
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class gevent --workers 1 --bind 0.0.0.0:$PORT app:app"
